# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/common-lib"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/mgmt-svc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/ingestion-svc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/app-ux"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/processor"
    schedule:
      interval: "weekly"