name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to our repository! Thank you for opening an issue. We will review it shortly."
        pr-message: "Hello! We appreciate your contribution through this pull request. We will review it as soon as possible."
