# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure Git
        run: |
          git config --global user.name "Release Bot"
          git config --global user.email "kcthota@gmail.com"
          git config --global credential.helper store
          echo "machine github.com login kcthota@gmail.com password ${{ github.token }}" > ~/.netrc

      - name: Build and release
        run: |
          mvn --batch-mode release:prepare release:perform -DskipTests
