name: Prepare release

on:
  workflow_dispatch:
    inputs:
      current_version:
        description: "Current release"
        default: "x.y.z"
      next_version:
        description: "Next release"
        default: "x.y.z-SNAPSHOT"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }}

      - name: Setup git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "BuildMan"

      - name: Build with Maven
        run: mvn release:prepare -Dtag=v${{ github.event.inputs.current_version }} -DreleaseVersion=${{ github.event.inputs.current_version }} -DdevelopmentVersion=${{ github.event.inputs.next_version }} -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.inputs.current_version }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn dockerfile:build dockerfile:tag dockerfile:push -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
